apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coffeshop
  namespace: jenkins
  name: coffeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeshop
  template:
    metadata:
      labels:
        app: coffeshop
    spec:
      containers:
      - image: omar20001/project:v1
        name: coffeshop
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        resources: {}
