apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
  name: service
  namespace: jenkins
spec:
  ports:
  - name: coffeshopport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: coffeshop
  type: LoadBalancer
status:
  loadBalancer: {}
